# Generated by Django 2.2.15 on 2020-08-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='published_date',
        ),
    ]
